apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-service.fullname" . }}
  labels:
    {{- include "laravel-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: php-fpm
  selector:
    {{- include "laravel-service.selectorLabels" . | nindent 4 }}
